#!/bin/bash
# Only upstream, checksum-pinned sources and project-local outputs are used.
set -euo pipefail
photo_project_root="$(cd "$(dirname "$0")/.." && pwd)"
source "$photo_project_root/scripts/project-env.sh"
photo_deps="$photo_project_root/.build/photo-deps"
photo_arch="${CROSSDIFF_ARCH:-$(uname -m)}"
case "$photo_arch" in arm64|x86_64) ;; *) echo "Unsupported OpenCV architecture: $photo_arch" >&2; exit 1;; esac
photo_install="$photo_deps/install-$photo_arch"
photo_stamp="opencv-4.12.0-core-imgproc-v3-macos14-$photo_arch"
if [[ -f "$photo_install/.crossdiff-build" ]] && [[ "$(cat "$photo_install/.crossdiff-build")" == "$photo_stamp" ]]; then
  exit 0
fi
mkdir -p "$photo_deps/downloads" "$photo_deps/tools"
photo_download() {
  local url="$1" destination="$2" expected="$3"
  if [[ ! -f "$destination" ]]; then
    curl --fail --location --retry 3 "$url" -o "$destination.partial"
    mv "$destination.partial" "$destination"
  fi
  local actual
  actual="$(shasum -a 256 "$destination" | cut -d ' ' -f 1)"
  [[ "$actual" == "$expected" ]] || { echo "Checksum mismatch: $(basename "$destination")" >&2; exit 1; }
}
photo_download https://codeload.github.com/opencv/opencv/tar.gz/refs/tags/4.12.0 \
  "$photo_deps/downloads/opencv-4.12.0.tar.gz" \
  44c106d5bb47efec04e531fd93008b3fcd1d27138985c5baf4eafac0e1ec9e9d
if command -v cmake >/dev/null 2>&1; then
  photo_cmake="$(command -v cmake)"
else
  photo_download https://github.com/Kitware/CMake/releases/download/v3.31.6/cmake-3.31.6-macos-universal.tar.gz \
    "$photo_deps/downloads/cmake-3.31.6-macos-universal.tar.gz" \
    330b9514f5112e5ed4fb08b8b05803b776fd9b539a6ae12927d14dcc0ee2ba8d
  if [[ ! -d "$photo_deps/tools/cmake-3.31.6-macos-universal" ]]; then
    tar -xzf "$photo_deps/downloads/cmake-3.31.6-macos-universal.tar.gz" -C "$photo_deps/tools"
  fi
  photo_cmake="$photo_deps/tools/cmake-3.31.6-macos-universal/CMake.app/Contents/bin/cmake"
fi
if [[ ! -d "$photo_deps/opencv-4.12.0" ]]; then
  tar -xzf "$photo_deps/downloads/opencv-4.12.0.tar.gz" -C "$photo_deps"
fi
"$photo_cmake" -S "$photo_deps/opencv-4.12.0" -B "$photo_deps/build-$photo_arch" \
  -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$photo_install" \
  -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF \
  -DCMAKE_OSX_ARCHITECTURES="$photo_arch" -DCMAKE_OSX_DEPLOYMENT_TARGET=14.0 \
  -DBUILD_LIST=core,imgproc -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF \
  -DBUILD_EXAMPLES=OFF -DBUILD_opencv_apps=OFF -DBUILD_JAVA=OFF -DBUILD_opencv_python2=OFF \
  -DBUILD_opencv_python3=OFF -DWITH_IPP=OFF -DWITH_ITT=OFF -DWITH_OPENCL=OFF \
  -DWITH_LAPACK=OFF -DWITH_EIGEN=OFF -DWITH_TBB=OFF -DWITH_OPENMP=OFF \
  -DWITH_ACCELERATE=OFF -DWITH_PROTOBUF=OFF -DWITH_ADE=OFF -DBUILD_ZLIB=OFF \
  -DWITH_CAROTENE=OFF -DWITH_JPEG=OFF -DWITH_PNG=OFF -DWITH_TIFF=OFF -DWITH_WEBP=OFF \
  -DWITH_OPENJPEG=OFF -DWITH_OPENEXR=OFF -DWITH_JASPER=OFF -DWITH_AVIF=OFF \
  -DOPENCV_ENABLE_NONFREE=OFF -DOPENCV_DOWNLOAD_PATH="$photo_deps/downloads" \
  -DOPENCV_FORCE_3RDPARTY_BUILD=OFF -DOPENCV_GENERATE_PKGCONFIG=OFF \
  -DCMAKE_CXX_FLAGS="-ffile-prefix-map=$photo_project_root=. -fdebug-prefix-map=$photo_project_root=."
# Prefix maps do not affect literal strings generated by CMake (build information
# and data-directory hints). Sanitize those generated inputs before compilation;
# never patch shipped binaries or alter the upstream image-analysis algorithms.
python3 - "$photo_deps/build-$photo_arch" "$photo_project_root" <<'PY'
from pathlib import Path
import sys
build = Path(sys.argv[1])
project = sys.argv[2]
for relative in ("version_string.tmp", "modules/core/version_string.inc", "opencv_data_config.hpp"):
    generated = build / relative
    original = generated.read_text()
    cleaned = original.replace(project, "<PROJECT>")
    if original != cleaned:
        generated.write_text(cleaned)
PY
"$photo_cmake" --build "$photo_deps/build-$photo_arch" --parallel "${CROSSDIFF_BUILD_JOBS:-4}"
"$photo_cmake" --install "$photo_deps/build-$photo_arch"
python3 - "$photo_install" "$photo_project_root" <<'PY'
from pathlib import Path
import subprocess
import sys
install = Path(sys.argv[1])
project = sys.argv[2].encode()
for library in ("libopencv_core.a", "libopencv_imgproc.a"):
    strings = subprocess.check_output(["/usr/bin/strings", str(install / "lib" / library)])
    if project in strings:
        raise SystemExit("OpenCV build still contains a project path: " + library)
PY
printf '%s\n' "$photo_stamp" > "$photo_install/.crossdiff-build"
